package com.til.prime.timesSubscription.enums;

public enum JobKeyEnum {
    SSO_COMMUNICATION,
    SUBSCRIPTION_RENEWAL,
    SUBSCRIPTION_FUTURE_ACTIVATION,
    SUBSCRIPTION_RENEWAL_REMINDER,
    SUBSCRIPTION_EXPIRY,
    SUBSCRIPTION_EXPIRY_REMINDER,
    EXPIRED_SUBSCRIPTION_RENEWAL_REMINDER;
}
