package com.til.prime.timesSubscription.enums;

public enum JobKeyEnum {
    SSO_COMMUNICATION,
    TRIAL_EXPIRY_REMINDER,
    TRIAL_EXPIRY,
    SUBSCRIPTION_EXPIRY_REMINDER,
    SUBSCRIPTION_EXPIRY,
    SUBSCRIPTION_RENEWAL,
    SUBSCRIPTION_RENEWAL_REMINDER,
    EXPIRED_TRIAL_SUBSCRIPTION_RENEWAL,
    EXPIRED_PAID_SUBSCRIPTION_RENEWAL;
}
