package com.til.prime.timesSubscription.service;

import com.til.prime.timesSubscription.dto.external.BackendSubscriptionActivationRequest;
import com.til.prime.timesSubscription.dto.external.BackendSubscriptionActivationResponse;
import com.til.prime.timesSubscription.dto.external.BackendSubscriptionRequest;
import com.til.prime.timesSubscription.dto.external.BackendSubscriptionResponse;
import com.til.prime.timesSubscription.dto.external.BlockUnblockRequest;
import com.til.prime.timesSubscription.dto.external.CancelSubscriptionRequest;
import com.til.prime.timesSubscription.dto.external.CancelSubscriptionResponse;
import com.til.prime.timesSubscription.dto.external.CheckEligibilityRequest;
import com.til.prime.timesSubscription.dto.external.CheckStatusRequest;
import com.til.prime.timesSubscription.dto.external.CheckStatusResponse;
import com.til.prime.timesSubscription.dto.external.CheckValidVariantRequest;
import com.til.prime.timesSubscription.dto.external.CustomerDetailsCRMResponse;
import com.til.prime.timesSubscription.dto.external.CustomerSearchCRMResponse;
import com.til.prime.timesSubscription.dto.external.CustomerSearchRequest;
import com.til.prime.timesSubscription.dto.external.ExtendExpiryRequest;
import com.til.prime.timesSubscription.dto.external.ExtendExpiryResponse;
import com.til.prime.timesSubscription.dto.external.GenerateOrderRequest;
import com.til.prime.timesSubscription.dto.external.GenerateOrderResponse;
import com.til.prime.timesSubscription.dto.external.GenericResponse;
import com.til.prime.timesSubscription.dto.external.GenericValidationResponse;
import com.til.prime.timesSubscription.dto.external.InitPurchaseRequest;
import com.til.prime.timesSubscription.dto.external.InitPurchaseResponse;
import com.til.prime.timesSubscription.dto.external.OrderDetailsCRMResponse;
import com.til.prime.timesSubscription.dto.external.OrderDetailsRequest;
import com.til.prime.timesSubscription.dto.external.OrderSearchCRMResponse;
import com.til.prime.timesSubscription.dto.external.OrderSearchRequest;
import com.til.prime.timesSubscription.dto.external.PlanListRequest;
import com.til.prime.timesSubscription.dto.external.PlanListResponse;
import com.til.prime.timesSubscription.dto.external.PropertyDataGetResponseCRM;
import com.til.prime.timesSubscription.dto.external.PropertyDataRequestCRM;
import com.til.prime.timesSubscription.dto.external.PropertyDataUpdateRequestCRM;
import com.til.prime.timesSubscription.dto.external.PurchaseHistoryRequest;
import com.til.prime.timesSubscription.dto.external.PurchaseHistoryResponse;
import com.til.prime.timesSubscription.dto.external.SubmitPurchaseRequest;
import com.til.prime.timesSubscription.dto.external.SubmitPurchaseResponse;
import com.til.prime.timesSubscription.dto.external.TurnOffAutoDebitRequest;
import com.til.prime.timesSubscription.dto.external.UpdateCacheForMobileRequest;
import com.til.prime.timesSubscription.dto.external.*;
import com.til.prime.timesSubscription.enums.EventEnum;
import com.til.prime.timesSubscription.model.BackendSubscriptionUserModel;
import com.til.prime.timesSubscription.model.UserModel;
import com.til.prime.timesSubscription.model.UserSubscriptionModel;

public interface SubscriptionService {
    PlanListResponse getAllPlans(PlanListRequest request);
    GenericResponse updateUsers();
    InitPurchaseResponse initPurchasePlan(InitPurchaseRequest request);
    InitPurchaseResponse initPurchasePlan(InitPurchaseRequest request, boolean crmRequest, boolean isFree);
    GenerateOrderResponse generateOrder(GenerateOrderRequest request);
    SubmitPurchaseResponse submitPurchasePlan(SubmitPurchaseRequest request);
    PurchaseHistoryResponse getPurchaseHistory(PurchaseHistoryRequest request);
    CancelSubscriptionResponse cancelSubscription(CancelSubscriptionRequest request, boolean serverRequest);
    GenericResponse turnOffAutoDebit(TurnOffAutoDebitRequest request);
    GenericResponse blockUnblockUser(BlockUnblockRequest request);
    ExtendExpiryResponse extendExpiry(ExtendExpiryRequest request);
    GenericValidationResponse checkEligibility(CheckEligibilityRequest request);
    GenericValidationResponse checkValidVariant(CheckValidVariantRequest request);
    CheckStatusResponse checkStatusViaApp(CheckStatusRequest request);
    CheckStatusResponse checkStatusViaServer(CheckStatusRequest request, boolean external);
    BackendSubscriptionResponse backendSubscriptionViaServer(BackendSubscriptionRequest request);
    BackendSubscriptionActivationResponse backendSubscriptionActivation(BackendSubscriptionActivationRequest request);
    UserModel getOrCreateUserWithMobileCheck(GenericRequest request, ValidationResponse validationResponse);
    UserSubscriptionModel saveUserSubscription(UserSubscriptionModel userSubscriptionModel, boolean retryForOrderId, String ssoId, String ticketId, EventEnum event, boolean communicateSSO);
    void updateUserStatus(UserSubscriptionModel userSubscriptionModel, UserModel userModel);
    UserModel saveUserModel(UserModel userModel, EventEnum eventEnum, boolean retryForPrimeId);
    void updateUserStatus(UserSubscriptionModel userSubscriptionModel);
    GenericResponse updateCacheForMobile(UpdateCacheForMobileRequest request);
    CustomerSearchCRMResponse customerSearchCRM(CustomerSearchRequest request);
    CustomerDetailsCRMResponse customerDetailsCRM(CustomerSearchRequest request);
    OrderDetailsCRMResponse getOrderDetailsCRM(OrderDetailsRequest request);
    OrderSearchCRMResponse orderSearchCRM(OrderSearchRequest request);
    GenericResponse sendOtp(OtpRequest request);
    OtpVerificationResponse verifyOtp(OtpVerificationRequest request);
    BackendSubscriptionUserModel saveBackendSubscriptionUser(BackendSubscriptionUserModel user, EventEnum eventEnum);
    PropertyDataGetResponseCRM getPropertyTableData(PropertyDataRequestCRM request);
    GenericResponse updatePropertyTableData(PropertyDataUpdateRequestCRM request);
}
